config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords',registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
  end
  
  
  
  root to: 'public_recipes#index'

  get '/recipes/general_shoping_list_total', to: 'recipes#general_shoping_list_total', as: 'general_shoping_list__total_recipe'
  resources :recipes do 
    

post :add, on: :member
get :cancel, on: :member
get :add_ingredient, on: :member
post :add_ingredient_alone, on: :member
post :delete_ingredient, on: :member
get :modify, on: :member
get :general_shoping_list, on: :member
post :modify_ingredient, on: :member
    end





  resources :recipe_foods
  resources :foods
  resources :users
  resources :public_recipes
  authenticated :user do
    root to: 'public_recipes#index', as: :authenticated_root
  end

  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, foreign_key: :recipe_id

  validates :name, length: { maximum: 100 }, presence: true
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!
  layout 'application'
  # GET /recipes or /recipes.json
  def index
    @style = 'recipes/index'
     return unless user_signed_in?

     @current_user = current_user
    @recipes = Recipe.where(user_id: current_user.id)
    
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @style = 'recipes/index'
    @activo = params[:activo] == 'true' 
    @foods = Food.all
    @recipe = Recipe.find(params[:id])
    @recipe_food = RecipeFood.where(recipe_id: params[:id])

    
    render partial: 'recipe_custom', locals: { recipe: @recipe }

end

def add_ingredient
  
  
  redirect_to action: "show", activo: 'true'
  
  
end

def add_ingredient_alone
  
  RecipeFood.create(quantity: '1.5', recipe_id: params[:recipe_id], food_id: params[:id])
  
  redirect_to action: "show", id: params[:recipe_id], activo: 'true'
  
end



def general_shoping_list
  @style = 'shoping/shoping'
@recipe_food = RecipeFood.where(recipe_id: params[:id])
@suma = 0 


  render "recipes/shoping_list"
end

def general_shoping_list_total
  @style = 'shoping/shoping'
  @recipe_food = RecipeFood.all
  @suma = 0 
  
    render "recipes/shoping_list"
  end


def modify 
  @style = 'shoping/modify'
  @recipefood = RecipeFood.new
  @recipeid = params[:recipe_id]
  @recipe_id = RecipeFood.find_by(id: params[:id])
  render "recipes/_edit_ingredient"

end

def modify_ingredient
  
  @recipefood = RecipeFood.find_by(id: params[:id])
  if @recipefood
    @recipefood.update(quantity: params[:recipe_food][:quantity])
    redirect_to recipe_path(params[:recipeid])
  else
  end
end


def delete_ingredient
RecipeFood.find(params[:id]).destroy
  redirect_to action: "show", id: params[:recipe_id], activo: 'true'
end

# GET /recipes/new
def new
  @style = 'recipes/new'
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @style = 'recipes/create'
    return unless user_signed_in?

    @current_user = current_user

    @recipe = Recipe.new(recipe_params.merge(user_id: @current_user.id))

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    # respond_to do |format|
    #   if @recipe.update(recipe_params)
    #     format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @recipe }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @recipe.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


def cancel
  redirect_to action: "show"
end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_edit_ingredient.html.erb
<section>
<%= form_with(model: @recipefood, url: modify_ingredient_recipe_path(recipeid: @recipeid)) do |form| %>
 

      
    <div>
      <%= form.label @recipe_id.food.name, style: "display: block" %>
      
    </div>
  
    <div>
      <%= form.label :Quantity, style: "display: block" %>
      <%= form.number_field :quantity %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>

<% end %>

</section>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "form_new_recipe") do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="recipe general_recipe">
  <p>
    <strong>Recipe: <%= recipe.id %></strong>
    <%= recipe.name %>
  </p>


  <p>
    <strong> Preparation time: <%= recipe.preparation_time %> hour</strong>
  </p>

  <p>
  <strong> Cooking time: <%= recipe.cooking_time %> hours</strong>
</p>

<%= link_to "Show this recipe", recipe %>
<%= button_to "Destroy this recipe", recipe, method: :delete , class: "button_delete_recipes"%>



</div>

app/views/recipes/_recipe_custom.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "recipes/custom" , "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <nav>
  <ul class="nav_bar">
    <li><%= link_to "Recipes", recipes_path %></li>
    <li><%= link_to "Public Recipes", public_recipes_path %></li>
    <li><%= link_to "Foods", foods_path %></li>
    <li><%= link_to "Shopping List", general_shoping_list__total_recipe_path %></li>    
    <li><%= link_to "Sing in", new_user_session_path %></li>
    <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
  </ul>
</nav>



  <body>
    <section>
<div id="<%= dom_id recipe %>" class="show_recipe">
  <p>
    <strong>Recipe: <%= recipe.id %></strong>
    <%= recipe.name %>
  </p>


  <p>
    <strong> Preparation time: <%= recipe.preparation_time %> hour</strong>
  </p>

  <p>
  <strong> Cooking time: <%= recipe.cooking_time %> hours</strong>
</p>




<p>
  <strong> Public:
   <%= @ispublic = recipe.public %>
   <% if @ispublic %>
   
   <input type="checkbox" checked name="example" id="example" data-toggle="switch" data-on-color="primary" data-off-color="default">
   <% else %>
   <input type="checkbox"  name="example" id="example" data-toggle="switch" data-on-color="primary" data-off-color="default">
   <% end%>
   
   
   hours</strong>
</p>


  <p>
    <strong>Description: </strong>
    <%= recipe.description %>
  </p>
  <%= button_to "Generate shoping list.", general_shoping_list_recipe_path(recipe), method: :get ,class: "button_show" %>
  <%= button_to "Add ingredient", add_ingredient_recipe_path(recipe), method: :get,class: "button_show" %>
  

<%if @activo == true%>
<div id="foods_table">
  <table>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Measurement Unit</strong></td>
      <td><strong>Price</strong></td>
      <td><strong>Quantity</strong></td>
      <td><strong>Actions</strong>
     
      
      </tr>  
      
      <% @foods.each do |food| %>
        
        <%= render partial: 'row_ingredients', locals: {food: food, recipe: recipe} %>
        <% end %>
        
        </table>  
        
        <%= button_to "Cancel", cancel_recipe_path(recipe), method: :get %>
      </div>
      
<% else %>

<% end %>


<div id="foods_table">
<table  class="table_add_ingredient">
<tr>
<td><strong>Food  </strong></td>
<td><strong>Quantity</strong></td>
<td><strong>Value</strong></td>
<td><strong>Actions</strong></td>



</tr>  
<% @recipe_food.each do |food| %>
        
  <%= render partial: 'row_ingredients_show', locals: {recipe_food: food, recipe_id: recipe} %>
<% end %>

</table>  



</div>
</div>

<%if @activo == true%>

<% else %>
<% end %>
<%= link_to "Back to recipes", recipes_path , class: "back_show_recipe"%>
</section>
  </body>
</html>

app/views/recipes/_row_ingredients.html.erb
<div id="<%= dom_id food %>">
  <tr>
    <td>
      <%= food.name %>
    </td>
    <td>
    <%= food.measurement_unit %>
    </td>
    <td>
      <%= food.price %>
    </td>

    <td>
      <%= food.quantity %>
    </td>


  
    <td>
    
    <%= button_to "Add",  add_ingredient_alone_recipe_path(food,recipe_id: recipe.id), method: :post %>
    </td>
    
  <tr>

  </div>

app/views/recipes/_row_ingredients_show.html.erb
<div>
  <tr>
    <td>
      <%= recipe_food.food.name %>
    </td>
    

    <td>
      <%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %> 
    </td>
    
    <td>
      <%= (recipe_food.quantity.to_f)*recipe_food.food.price %>
    </td>
    
    <td>    
     
     <%= link_to "Modify", modify_recipe_path(recipe_food, recipe_id: recipe_id.id) %>

    </td>
    <td>    
     <%= button_to "Remove", delete_ingredient_recipe_path(recipe_food, recipe_id: recipe_id.id), method: :post %>
    </td>
    
  <tr>
</div>

app/views/recipes/_row_shoping_list.html.erb
<div id="<%= dom_id food %>">
  <tr>
    <td>
      <%= food.food.name %>
    </td>

    <td>
      <%= food.quantity %> 
    </td>

    <td>
    <%= (food.quantity.to_f)*food.food.price %>
    </td>
  <tr>

  </div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<section >
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      
      
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path, class: 'add_new_recipe' %>
</section>

app/views/recipes/new.html.erb
<section>
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>
</section>

app/views/recipes/shoping_list.html.erb
<section>
<h1>Shopping List</h1>

<h2>Amount of food items to buy: <%= @recipe_food.count%> </h2>
<h2>Total value fo food needed:
 

<% @recipe_food.each do |e| %> 
    <% @suma += (e.food.price)* e.quantity.to_f %>
<% end %>
 <%= @suma %>   
 
 </h2>


 <table>
 <tr>
   <td><strong>Food</strong></td>
   <td><strong>Quantity</strong></td>
   <td><strong>Price</strong></td>
   
  
   
   </tr>  
   
   <% @recipe_food.each do |food| %>
     
     <%= render partial: 'row_shoping_list', locals: {food: food} %>
     <% end %>
     
     </table>  
     </section>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div>
   |
  <%= link_to "Back to recipes", recipes_path %>

  
</div>