config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords',registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
  end
  
  
  
  root to: 'public_recipes#index'

  get '/recipes/general_shoping_list_total', to: 'recipes#general_shoping_list_total', as: 'general_shoping_list__total_recipe'
  resources :recipes do 
    

post :add, on: :member
get :cancel, on: :member
get :add_ingredient, on: :member
post :add_ingredient_alone, on: :member
post :delete_ingredient, on: :member
get :modify, on: :member
get :general_shoping_list, on: :member
post :modify_ingredient, on: :member
    end





  resources :recipe_foods
  resources :foods
  resources :users
  resources :public_recipes
  authenticated :user do
    root to: 'public_recipes#index', as: :authenticated_root
  end

  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, foreign_key: 'food_id'
  

  validates :name, length: { maximum: 80 }, presence: true
  validates :price, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /foods or /foods.json
  def index
    @style = 'foods/index'
    @foods = Food.order(params[:sort])
   
  end

  # GET /foods/1 or /foods/1.json
  def show
  @style = 'foods/show'
  end
  # GET /foods/new
  def new
    @style = 'foods/new'
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @style = 'foods/create'
    return unless user_signed_in?

    @current_user = current_user
    
    @food = Food.new(food_params.merge(user_id: @current_user.id))

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    return unless user_signed_in?

    @current_user = current_user

    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id => @current_user.id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <tr>
    <td>
      <%= food.name %>
    </td>

    <td>
      <%= food.measurement_unit %>
    </td>

    <td>
      <%= food.price %>
    </td>
  
    <td>
    <%= button_to "Destroy this food", food, method: :delete %>
    </td>
  <tr>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>
  
<section class="foods-index">
<h1>Foods</h1>
<button class="foods_newButton"><%= link_to "Add new food", new_food_path %></button>

<div class="foods_table">
  <table>
    <tr>
      <td><strong>Name</strong> </td>
      <td><strong>Measurement Unit</strong></td>
      <td><strong>Price</strong></td>
      <td><strong>Actions</strong>
     

    </tr>  
    
  <% @foods.each do |food| %>
     <%= render food %>
  <% end %>
  
  </table>  




</div>


</section>

app/views/foods/new.html.erb
<section>

<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

</section>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>
<section>
<h2>Food Added!</h2>

<div>
  
  <%= link_to "Back to foods", foods_path %>

  
</div>
</section>