config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords',registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
  end
  
  
  
  root to: 'public_recipes#index'

  get '/recipes/general_shoping_list_total', to: 'recipes#general_shoping_list_total', as: 'general_shoping_list__total_recipe'
  resources :recipes do 
    

post :add, on: :member
get :cancel, on: :member
get :add_ingredient, on: :member
post :add_ingredient_alone, on: :member
post :delete_ingredient, on: :member
get :modify, on: :member
get :general_shoping_list, on: :member
post :modify_ingredient, on: :member
    end





  resources :recipe_foods
  resources :foods
  resources :users
  resources :public_recipes
  authenticated :user do
    root to: 'public_recipes#index', as: :authenticated_root
  end

  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag @style , "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <nav>
  <ul class="nav_bar">
    <li><%= link_to "Recipes", recipes_path %></li>
    <li><%= link_to "Public Recipes", public_recipes_path %></li>
    <li><%= link_to "Foods", foods_path %></li>
    <li><%= link_to "Shopping List", general_shoping_list__total_recipe_path %></li>
    <li><%= link_to "Sing in", new_user_session_path %></li>
    <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
  </ul>
</nav>



  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/nav_bar.html.erb
<nav>
  <ul>
    <li><%= link_to "Recipes", recipes_path %></li>
    <li><%= link_to "Public Recipes", public_recipes_path %></li>
    <li><%= link_to "Foods", foods_path %></li>
    <li><%= link_to "Shoping list", general_shoping_list_total_recipe_path(@idelement) %></li>
    <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
  </ul>
</nav>